### ISSUE TITLE
the code in the book is different

### ISSUE THREAD

**Issue by alfonsovgs** [PacktPublishing/Microservices-with-Go#4]
Why is the code in the book different from the code in the repository?

Example
![image](https://user-images.githubusercontent.com/10533637/209564500-4b908de5-f445-46d9-bf4e-f24dcc97dbb6.png)

Reference code
https://github.com/PacktPublishing/Microservices-with-Go/blob/main/Chapter05/src/movie/internal/gateway/metadata/grpc/metadata.go#L30

**Comment by packt-pradeeps** [comment]
@b441berith Please have a look into this issue.

**Comment by b441berith** [comment]
My fault, the correct version is GetMetadata. This was a (useful) proposal by my reviewer — initial GetMetadataByID is a less flexible approach, because it supports only id-based retrieval. GetMetadata is more flexible and leaves a room for future changes, such as name-based lookups. I tried to update all references throughout the book but seems that one left unchanged — thanks for pointing out!
