### ISSUE TITLE
Chapter 03. The in-memory service discovery is returning new map each time

### ISSUE THREAD

**Issue by mkvy** [PacktPublishing/Microservices-with-Go#6]
In-memory service discovery factory implemented as:
```
func NewRegistry() *Registry {
	return &Registry{serviceAddrs: map[string]map[string]*serviceInstance{}}
}
```
So if it's called in every main file `registry := memory.NewRegistry()` it recieves registry instance with new, empty map, so each instance registers itself in it's own map and you can't discover other instances. It should have singleton in factory or something.

**Comment by b441berith** [comment]
You are right, the implementation would be usable only if all services are ran within the same process space. While this is certainly not the type of configuration that would be used in production, this is still useful for integration testing: https://github.com/PacktPublishing/Microservices-with-Go/blob/main/Chapter09/src/test/integration/main.go
This is why the service code is using the Consul-based discovery: https://github.com/PacktPublishing/Microservices-with-Go/blob/main/Chapter03/src/metadata/cmd/main.go
So I would suggest to still leave the implementation since its useful for integration testing, with a note that its only for testing and illustrative purposes.
